### ISSUE TITLE
activescaffold cancan production problem

### ISSUE THREAD

**Issue by barriault** [ryanb/cancan#525]
I'm getting this weird error in production and not in development:

```
CanCan::AuthorizationNotPerformed in ContactsController#index

This action failed the check_authorization because it does not authorize_resource. Add skip_authorization_check to bypass this check.
```

I have plenty of other models/controllers authorized by Cancan that
work fine. The only one I seem to have any problems with is this one.

I've even reduced my ability.rb file to this:

```
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :all
  end
end
```

Any ideas on what might be causing this or where I should look?

**Comment by piousbox** [comment]
This happens to me as well. Same error, in production only. In development it works fine.

**Comment by piousbox** [comment]
Further, I think this happens when the cache is generated (i.e. on the 2nd time I hit the page). Since development has no caching, I suspect this problem is related to caching.

<pre>
class SitesController < ApplicationController
  caches_action :show, self::CACHE_OPTIONS
  caches_action :features, self::CACHE_OPTIONS
  load_and_authorize_resource
  def show
    authorize! :show, Site.new
    ... <other code> ...
  end
  ... <other code> ...
end
</pre>
